apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-user-service
  labels:
    app: fcg-user-service
spec:
  replicas: 1 # O HPA ajusta automatico
  selector:
    matchLabels:
      app: fcg-user-service
  template:
    metadata:
      labels:
        app: fcg-user-service
    spec:
      containers:
      - name: fcg-user-service
        image: 363256880455.dkr.ecr.sa-east-1.amazonaws.com/fcg-user-service
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: fcg-user-service-config
        - secretRef:
            name: fcg-user-service-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
